# Generated by Django 3.1.4 on 2021-03-14 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=127, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=127)),
                ('last_name', models.CharField(max_length=127)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('rating', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stakeholders',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Strengths',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stakeholder', models.ManyToManyField(related_name='s_stakeholder', to='abcd.Stakeholders')),
                ('tag', models.ManyToManyField(related_name='s_tag', to='abcd.Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Qualities',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stakeholder', models.ManyToManyField(related_name='q_stakeholder', to='abcd.Stakeholders')),
                ('tag', models.ManyToManyField(related_name='q_tag', to='abcd.Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Possesses',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset', models.ManyToManyField(related_name='p_asset', to='abcd.Assets')),
                ('institution', models.ManyToManyField(related_name='p_institution', to='abcd.Institutions')),
            ],
        ),
        migrations.CreateModel(
            name='Owns',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset', models.ManyToManyField(related_name='o_asset', to='abcd.Assets')),
                ('stakeholder', models.ManyToManyField(related_name='o_stakeholder', to='abcd.Stakeholders')),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stakeholder', models.ManyToManyField(related_name='i_stakeholder', to='abcd.Stakeholders')),
                ('tag', models.ManyToManyField(related_name='i_tag', to='abcd.Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Belongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.ManyToManyField(related_name='b_institution', to='abcd.Institutions')),
                ('stakeholder', models.ManyToManyField(related_name='b_stakeholder', to='abcd.Stakeholders')),
            ],
        ),
    ]
